In [9]:
import numpy as np
import cv2
import tensorflow as tf

In [ ]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y

In [ ]:
with tf.Session() as sess:
    print(sess.run([z], feed_dict={x:12.0, y:24.0}))

In [7]:
%%bash
curl https://as01.epimg.net/en/imagenes/2017/06/26/football/1498464359_923447_1498468477_sumario_normal.jpg -o messi.jpg

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 29526  100 29526    0     0  28437      0  0:00:01  0:00:01 --:--:-- 28445


In [10]:
img = cv2.imread('messi.jpg',0)

In [11]:
print(img)

[[16 16 17 ... 25 26 28]
 [16 16 17 ... 25 27 29]
 [16 16 17 ... 26 28 30]
 ...
 [48 48 49 ... 44 40 41]
 [48 48 49 ... 47 43 42]
 [48 48 49 ... 50 45 42]]


In [17]:
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()